module.exports = {
  schemaQuery(table) {
    return `DESCRIBE \`${table}\``;
  },
  keyQuery(table) {
    // SELECT
    //   *
    // FROM
    //   INFORMATION_SCHEMA.KEY_COLUMN_USAGE
    // LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
    //   ON INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME = INFORMATION_SCHEMA.KEY_COLUMN_USAGE.CONSTRAINT_NAME
    //   AND INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.TABLE_NAME = '${table}'
    //   AND INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.CONSTRAINT_SCHEMA = '${process.env.DB_SCHEMA}'
    // LEFT JOIN INFORMATION_SCHEMA.STATISTICS
    //   ON INFORMATION_SCHEMA.STATISTICS.INDEX_NAME = INFORMATION_SCHEMA.KEY_COLUMN_USAGE.CONSTRAINT_NAME
    //   AND INFORMATION_SCHEMA.STATISTICS.TABLE_NAME = '${table}'
    //   AND INFORMATION_SCHEMA.STATISTICS.TABLE_SCHEMA = '${process.env.DB_SCHEMA}'
    // WHERE
    //   INFORMATION_SCHEMA.KEY_COLUMN_USAGE.TABLE_SCHEMA = '${process.env.DB_SCHEMA}' AND
    //   INFORMATION_SCHEMA.KEY_COLUMN_USAGE.TABLE_NAME = '${table}'
    return `
      SELECT
        COLUMN_NAME,
        INDEX_NAME AS 'KEY_NAME',
        IF(NON_UNIQUE, 0, 1) AS 'UNIQUE',
        SUB_PART AS 'LENGTH'
      FROM
        INFORMATION_SCHEMA.STATISTICS
      WHERE
        INFORMATION_SCHEMA.STATISTICS.TABLE_SCHEMA = '${process.env.DB_SCHEMA}' AND
        INFORMATION_SCHEMA.STATISTICS.TABLE_NAME = '${table}';

      SELECT
        COLUMN_NAME,
        INFORMATION_SCHEMA.KEY_COLUMN_USAGE.CONSTRAINT_NAME AS 'KEY_NAME',
        INFORMATION_SCHEMA.KEY_COLUMN_USAGE.REFERENCED_TABLE_NAME,
        REFERENCED_COLUMN_NAME,
        UPDATE_RULE,
        DELETE_RULE
      FROM
        INFORMATION_SCHEMA.KEY_COLUMN_USAGE
      LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
        ON INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME = INFORMATION_SCHEMA.KEY_COLUMN_USAGE.CONSTRAINT_NAME
        AND INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.TABLE_NAME = '${table}'
        AND INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS.UNIQUE_CONSTRAINT_SCHEMA = '${process.env.DB_SCHEMA}'
      WHERE
        INFORMATION_SCHEMA.KEY_COLUMN_USAGE.TABLE_SCHEMA = '${process.env.DB_SCHEMA}' AND
        INFORMATION_SCHEMA.KEY_COLUMN_USAGE.TABLE_NAME = '${table}' AND
        INFORMATION_SCHEMA.KEY_COLUMN_USAGE.REFERENCED_TABLE_NAME IS NOT NULL;
    `;
  },
};
